### ISSUE TITLE
SSL URL

### ISSUE THREAD

**Issue by UKChris-osm** [ideditor/location-conflation#33]
The domain name [location-conflation.com](http://location-conflation.com) doesn't appear to be redirecting to the secure (SSL) site, such as when clicking a location link from the [nsi.guide](https://nsi.guide) web site.

In the case of the NSI, the domain being used it https://ideditor.github.io/location-conflation/?referrer=nsi which is then redurected to the non-ssl version of location-conflation.com

**Comment by UKChris-osm** [comment]
Updated NSI to use new domain via [ff4c492](https://github.com/osmlab/name-suggestion-index/commit/ff4c49286c169ac89c44967760546eee4bfc7b27)

**Comment by bhousel** [comment]
Thanks!  I just clicked the button in the dashboard to redirect all traffic to the ssl url.. Let me know if that's working...

**Comment by UKChris-osm** [comment]
All working now 👍
